### PR TITLE
Deep encoding of pipes

### PR DESCRIPTION
**Pull request by dhil**
A deep encoding of the pipes example from Kammar, Lindley, and Oury, "Handlers in Action", ICFP 2013.

### CODE REVIEW

**Comment by kayceesrk** [comment]
@dhil Thanks for the example. Can you update the index in the README as well?

**Comment by dhil** [comment]
Done!

**Comment by kayceesrk** [comment]
Conflicts still? Can you do a pull from upstream and check?

**Comment by dhil** [comment]
Apologies, I did not notice. Now it's [Done Done](http://www.jamesshore.com/Agile-Book/done_done.html).

**Comment by kayceesrk** [comment]
👍 Thanks!

**Pull request merged**
